name: On Issue Created

on:
  issues:
    types: [opened]

jobs:
  call-workflow:
    uses: ./.github/workflows/wf-reusable-example.yaml
    with:
      environment: 'staging'
  call-workflow2:
    uses: ./.github/workflows/wf-echo-secrets.yaml
