name: echo secrets

on:
  workflow_call:
    secrets:
      SUPERSECRET:
        required: true

jobs:
  echo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo super secret
        run: echo ${{ secrets.SUPERSECRET }}
