name: On Issue Created

on:
  issues:
    types: [opened]

jobs:
  call-workflow3:
    uses: ./.github/workflows/wf-output-example.yaml

  check-output:
    runs-on: ubuntu-latest
    # needs で call-workflow3 のジョブが完了するまで待つ
    needs: call-workflow3
    steps:
      - name: Check build output
        run: echo ${{ needs.call-workflow3.outputs.build }}
      - name: Check test output
        run: echo ${{ needs.call-workflow3.outputs.test }}
